

var response = prompt("Rain falls in heavy waves against the car and your windshield wipers can barely keep up. You sigh and switch to the highest speed and slow to a crawl on the highway. There aren't many cars out on this road, which is odd. It's Friday night and traffic is, usually, jam-packed by this hour. You check the clock on the speed dial to see that it's only 6:22 pm. The sun has already completed its trek across the sky but there is still a sliver of light giving an odd fire like glaze, everywhere. You fix your attention back on the road and notice that the car in front of you is driving a little crazy. A little crazy becomes a lot of crazy when they start swerving wildly, hitting the cars in the adjoining lane. You stare transfixed at the scene unfolding before you and it abruptly ends when the car finally swerves too hard and has a full on collision with a car in the far right lane. Everyone, including you, seems to slow down or stop their car completely. CLICK OK.");

var response = prompt("A 4x4 honks obnoxiously before swerving around everyone and continuing past the accident as if they don't see it. You contemplate doing the same but your conscious is protesting loudly. It's been a long week and you're tired. You put in 12 hours of overtime this week and you just want to go home and relax. Do you drive around the accident or stop to help? To drive around type [Drive] to stop and help type [Stop]")

if(response === "Drive") {
  response = prompt("You decide to drive around the accident but without all the theatrics of the 4x4. You inch by the other cars while trying to get a glimpse of all the commotion. You see a man knocking on the window of the car that caused the accident. There seems to be a lot of commotion coming from inside the car. It's as if whoever is in there is having a seizure or fighting someone. Another man who's tall and burly is stomping over to the perpetrator's car and you can tell that he came from the car that was hit. Just as the scene is about to fall out of sight you notice the man knocking on the window jump back from the car with a frightened look on his face. You shake your head and make the rest of the uneventful trip back to your home. Once inside your house do you go to the living room and turn on the news or call your friend to see if they wanted to come over to watch a movie? Type [LivingRoom] or [CallFriend]");
  if(response === "LivingRoom") {
    response = prompt("You go to the living room and fall onto the couch. You rub your eyes tiredly and pick up the remote. You pass through a few channels with nothing really catching your interest. You decide to turn to the news. Your two favorite newscasters are on but you sit up straight when you notice how dour they look. Francesca and Billy, usually, have an upbeat vibe to their show but not tonight. 'There seems to be a fast spreading flu epidemic. We don't have much information to give right now but everyone is being urged to stay in their home. The president will be giving an impromptu State of the Union at 8pm, please stay tuned.' You haven't heard anything about the flu and they, definitely, knew more than they are telling. Regardless, you start to get worried. You wonder about your brother who's the only family you have left. If things go bad you would rather be with him but he's having family issues right now. Should you call him? [CallBrother] or [Don't Call]");
    if(response === "CallBrother") {
      response = prompt("You call your brother Michael. His voice is a bit groggy as if he were sleeping. You ask him if he's heard the news and he's surprised. He says that his wife took the children and left the prior night and he'd only just been able to sleep. You feel bad but in the event of a quarantine, or whatever was happening, you would rather tough it out with him. He tells you to come over and he's going to check on his family. Do you hop in the car now or wait until Michael checks if his family is okay? [Go] or [Wait]");
      if(response === "Go") {
        response = prompt("You decide to try to go now and grab your keys and jacket. Before you can open your front door it rumbles under the weight of someone banging on it. Before you can ask who it is a sound like somenoe is being rammed into the door and a horrible scream full of pain pierces your ears. You inch to the side to peak out the corner of the only window that oversees your front porch and nearly scream at what you see. Your annoying neighbor, Stedmon, appears to be.....eating his wife Macy. You feel the contents of your stomach making its way to your throat and you hurriedly rush to the first floor bathroom. You make it just in time to empty the lunch you ate earlier. You dry heave for a few moments while trying to wrap your head around what you saw. You wash your mouth and face before going to the closet in the hallway where you keep your gun. You grab it out of its secret compartment with shaking hands. Should you call the [Police] or [Handle] it yourself?");
        if(response === "Police");
        response = prompt("Although, you're comfortable with wielding a gun, you are not comfortable with confronting whatever it is that's going on outside. You grab your cell-phone out of your pocket and dial 911. All you get is a recorded message saying that the line is busy and to be patient for assistance. You nearly growl in frustration. Now what do you do? You definitely don't see the front door as an exit anymore. Do you go through the back door or climb out of the living room window that adjoins the porch? [BackDoor] or [Window]");
          if(resonse === "BackDoor");
          response = prompt("You head towards the back door and pick up an emergency bag you always keep around in the event of a severe storm. You unlock and push slowly on the back door knowing the loud creaking noise it makes. You're not sure, exactly, what's going on but you don't want to cause any, unecessary, noise.")
      }
    }
    }
  }

if(response === "left") {
  response = prompt("You turn the knob on the left door. You do it slowly, as you expect it to creak, but you are surprised when it swings open, soundlessly. The room is bare, save for an antique crib in the corner. There is a baby blanket on the floor next to the crib and you creep closer to look at it. The blanket looks white but seems to be stained with a dark substance. Your eyes flit to the crib and notice that it, also, is covered in the dark substance. You begin to shiver in revulsion when you realize that the substance you are looking at is blood. You turn and bolt from the room seeking an exit, immediately. You intend to bolt back down the hallway but you see a woman in tattered clothes leaning against the wall. If you approach the woman type 'Approach', if you run further down the hall type 'run', if you decide to go in the door on the right type 'right'");

if(response === "approach") {
  response = prompt("Although, you are shaking and your heart is beating furiously against your rib-cage you stride purposely towards the woman. She looks up as she hears your footsteps and you are frozen solid by the milky whites of her eyes. Your mouth opens in a soundless scream and the woman begans to stagger slowly towards you. Just as you finally begin to mobilize the woman reaches for you with a load moan. To push her away type 'push', to side-step her and run back towards the door type 'door'");

} else if(response === "run") {
    response = prompt("You turn and run back deeper down the hall until you pass the two doors and enter into what seems to be a foyer. The design of the house confuses you but you don't linger on the fact. You look around frantically for something you can use as a weapon. There is a small wooden table with a vase of long dead flowers in front of you. You could use the vase but it would be wholly ineffective in the long run. There is an archway to your right and you can see a glimpse of a stove and counter. Do you grab the 'vase' as a weapon or do you head into the 'kitchen' for something better?");


} else if (response === "stairs") {
  response = prompt("You head slowly up the stairs, each step creaking ominously beneath your feet. Every step you take brings up a cloud of dust from the oriental design of the carpet beneath your feet. You get the feeling you are the first person to be in here in ages. At the top of the stairs there are two hallways winding to the left and the right. Type 'left' to go down the left hallway, type 'right' to go down the right hallway");

} else {
  alert("Please type in a valid input! Refresh the page to try again.");
}}}}
